### ISSUE TITLE
Issue with ondano sdk remote repos.

### ISSUE THREAD

**Issue by serhiiLiubetskyiI** [ondato/ondato-sdk-android#16]
Hi, I can't build a project because of ondato sdk repo issues. Could you help with this?
Could not find com.gemalto.jp2:jp2-android:1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://repo.maven.apache.org/maven2/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://repo1.maven.org/maven2/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://zendesk.jfrog.io/zendesk/repo/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://jitpack.io/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://raw.githubusercontent.com/ondato/ondato-sdk-android/main/repos/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
       - https://jcenter.bintray.com/com/gemalto/jp2/jp2-android/1.0/jp2-android-1.0.pom
     Required by:
         project :app > com.kyc.ondato:sdk:2.5.6

**Comment by ondato-mobile** [comment]
Try it with [2.5.7](https://github.com/ondato/ondato-sdk-android/releases/tag/2.5.7)

**Comment by serhiiLiubetskyiI** [comment]
FAILURE: Build failed with an exception.
* What went wrong:
Configuration cache state could not be cached: field `__projectRuntimeLintModelsFileCollection__` of `com.android.build.gradle.internal.lint.AndroidArtifactInput` bean found in field `__mainArtifact__` of `com.android.build.gradle.internal.lint.VariantInputs` bean found in field `__variantInputs__` of task `:feature:identity-verification:data:generateProdReleaseLintReportModel` of type `com.android.build.gradle.internal.lint.LintModelWriterTask`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':feature:identity-verification:data:prodReleaseRuntimeClasspath'.
   > Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
     Required by:
         project :feature:identity-verification:data > com.kyc.ondato:sdk:2.5.7
      > Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
         > Could not get resource '[https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'](https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom).
            > Could not GET '[https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'](https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom). Received status code 401 from server: Unauthorized
It still doesn't work

**Comment by maheshshende** [comment]
Hi Guys, Any update on above issue. I am also started get same error from this morning, We are using SDK 2.5.7. Urgent help in this regard will be highly applicated.

Error:

`Required by:
         project :app > com.kyc.ondato:sdk:2.5.7
> Could not find cz.adaptech.android:tesseract4android:2.1.0.
     Searched in the following locations:
       -
https://dl.google.com/dl/android/maven2/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom
       -
https://jcenter.bintray.com/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom
       - file:/D:/Abhishek/Workspace/deVere-Vault/deVere-Vault/app/lib/tesseract4android-2.1.0.jar
       - file:/D:/Abhishek/Workspace/deVere-Vault/deVere-Vault/app/lib/tesseract4android.jar
       -
https://raw.githubusercontent.com/ondato/ondato-sdk-android/main/repos/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom
       -
https://maven.microblink.com/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom
     Required by:
         project :app > com.kyc.ondato:sdk:2.5.7`

`> Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
     Required by:
         project :app > com.kyc.ondato:sdk:2.5.7
> Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
> Could not get resource '
https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'.
> Could not GET '
https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'.
Received status code 401 from server: Unauthorized`

**Comment by ondato-mobile** [comment]
Updated the dependency, please try 2.5.8

**Comment by MaximSamolovov** [comment]
I also get this error, the version of ondato in the **ondato-sdk-flutter** package is **2.5.10**

> > Could not find cz.adaptech.android:tesseract4android:2.1.0. Searched in the following locations: 

Required by:
         project :app > project :ondato_flutter > com.kyc.ondato:sdk:2.5.10
         
        
Do you have any suggestions on how to fix this?

**Comment by ondato-mobile** [comment]
@MaximSamolovov please add `maven { url 'https://jitpack.io/' }` to you project, that should solve it.

**Comment by MaximSamolovov** [comment]
> @MaximSamolovov please add `maven { url 'https://jitpack.io/' }` to you project, that should solve it.

maven { url "https://raw.githubusercontent.com/ondato/ondato-sdk-android/main/repos/" }
maven { url 'https://jitpack.io' }

I added it according to the instructions - still the same errors, everything is fine on 2.5.11. updated to 2.5.13 - the same error again

**Comment by ondato-mobile** [comment]
@MaximSamolovov Released [2.5.14](https://github.com/ondato/ondato-sdk-android/releases/tag/2.5.14). Let us know if you encounter any more issues
